# Generated by Django 6.0.2 on 2026-02-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart_alter_product_sale_price_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='product',
        ),
    ]
