openapi: 3.0.3
info:
  title: E-Mart API
  version: 1.0.0
  description: Comprehensive API for the E-Mart E-commerce platform.
paths:
  /api/auth/login/:
    post:
      operationId: auth_login_create
      description: Login endpoint that returns access and refresh tokens along with
        user data.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPair'
        required: true
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTokenObtainPair'
          description: ''
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      description: Logout endpoint that blacklists the refresh token.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
          description: ''
  /api/auth/me/:
    get:
      operationId: auth_me_retrieve
      description: Get the current authenticated user's profile.
      tags:
      - auth
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/auth/profile/:
    patch:
      operationId: auth_profile_partial_update
      description: Update the current user's profile.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/auth/refresh/:
    post:
      operationId: auth_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/auth/signup/:
    post:
      operationId: auth_signup_create
      description: Register a new user and return tokens.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUp'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SignUp'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SignUp'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUp'
          description: ''
  /api/cart/add/:
    post:
      operationId: cart_add_create
      description: |-
        Add a product to a cart identified by cart_code.
        If the cart does not exist, it will be created.
        If the product already exists in the cart, its quantity is incremented.
      tags:
      - cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cart_code:
                  type: string
                product_id:
                  type: integer
                quantity:
                  type: integer
                  default: 1
              required:
              - cart_code
              - product_id
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
          description: ''
  /api/cart/clear/:
    delete:
      operationId: cart_clear_destroy
      description: Clear all items from a cart.
      tags:
      - cart
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
          description: ''
  /api/cart/get/:
    get:
      operationId: cart_get_retrieve
      description: Get cart details by cart_code.
      parameters:
      - in: query
        name: cart_code
        schema:
          type: string
        description: The unique code for the cart
        required: true
      tags:
      - cart
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
          description: ''
  /api/cart/remove/:
    delete:
      operationId: cart_remove_destroy
      description: Remove a product from cart.
      tags:
      - cart
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
          description: ''
  /api/cart/update/:
    patch:
      operationId: cart_update_partial_update
      description: Update quantity of a product in cart.
      tags:
      - cart
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cart_code:
                  type: string
                product_id:
                  type: integer
                quantity:
                  type: integer
              required:
              - cart_code
              - product_id
              - quantity
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
          description: ''
  /api/categories/:
    get:
      operationId: categories_list
      description: Returns a list of all categories.
      tags:
      - categories
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryList'
          description: ''
  /api/categories/{slug}/:
    get:
      operationId: categories_retrieve
      description: Returns details of a single category along with its products.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - categories
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDetail'
          description: ''
  /api/products/:
    get:
      operationId: products_list
      description: |-
        Returns a list of all products with filtering, sorting, and pagination.
        Filtering: ?category=<slug>&featured=true
        Sorting: ?ordering=price or ?ordering=-price
      parameters:
      - in: query
        name: category__slug
        schema:
          type: string
      - in: query
        name: featured
        schema:
          type: boolean
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - products
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProductListList'
          description: ''
  /api/products/{slug}/:
    get:
      operationId: products_retrieve
      description: Returns details of a single product identified by its slug.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - products
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetail'
          description: ''
components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        cart_code:
          type: string
          maxLength: 11
        cartitems:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
          readOnly: true
        cart_total:
          type: number
          format: float
          readOnly: true
      required:
      - cart_code
      - cart_total
      - cartitems
      - id
    CartItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        product:
          allOf:
          - $ref: '#/components/schemas/ProductList'
          readOnly: true
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        sub_total:
          type: number
          format: float
          readOnly: true
      required:
      - id
      - product
      - sub_total
    CategoryDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        image:
          type: string
          format: uri
          nullable: true
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductList'
          readOnly: true
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - id
      - name
      - products
    CategoryList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        image:
          type: string
          format: uri
          nullable: true
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
      required:
      - id
      - name
    CustomTokenObtainPair:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    PaginatedProductListList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/ProductList'
    PatchedUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 100
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        role:
          $ref: '#/components/schemas/RoleEnum'
        avatar:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        email_verified:
          type: boolean
          readOnly: true
    ProductDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        image:
          type: string
          format: uri
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        discount:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        sale_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        rating:
          type: number
          format: double
        reviews_count:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        featured:
          type: boolean
        category:
          type: integer
          nullable: true
      required:
      - description
      - id
      - image
      - name
      - price
    ProductList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        slug:
          type: string
          maxLength: 50
          pattern: ^[-a-zA-Z0-9_]+$
        description:
          type: string
        image:
          type: string
          format: uri
        sale_price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          nullable: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        discount:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        rating:
          type: number
          format: double
        reviews_count:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
      required:
      - description
      - id
      - image
      - name
      - price
    RoleEnum:
      enum:
      - customer
      - admin
      - seller
      type: string
      description: |-
        * `customer` - Customer
        * `admin` - Admin
        * `seller` - Seller
    SignUp:
      type: object
      properties:
        email:
          type: string
          format: email
          maxLength: 100
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        password:
          type: string
          writeOnly: true
          minLength: 6
        password_confirm:
          type: string
          writeOnly: true
          minLength: 6
      required:
      - email
      - first_name
      - last_name
      - password
      - password_confirm
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 100
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        role:
          $ref: '#/components/schemas/RoleEnum'
        avatar:
          type: string
          format: uri
          nullable: true
          maxLength: 200
        email_verified:
          type: boolean
          readOnly: true
      required:
      - email
      - email_verified
      - first_name
      - id
      - last_name
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
