import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import LayoutWrapper from "@/components/layout/layoutWrapper";
import { AuthProvider } from "@/components/auth/AuthProvider";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} antialiased`}>
        <AuthProvider>
          <LayoutWrapper>
            <main className="w-full">
              {children}
            </main>
          </LayoutWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
